version: "3"
services:
  db:
    image: postgres:9.5
  sut:
    build: .
    command: sh /code/test.sh
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      - CODACY_PROJECT_TOKEN=e3745ba9ac04410c965ad9766fe6b69d
    env_file:
      - test.env
