# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_communication_preferred_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationtemplate',
            name='template',
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='short_message',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
