# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 20:13
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170713_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='sent', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='communication',
            name='sender',
        ),
        migrations.AddField(
            model_name='communication',
            name='backend_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='object_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='communication',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='last_sent_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='recipient_channel',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='recipient_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, db_index=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='communication',
            name='recipient_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='recipient_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='send_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='communication',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('S', 'Sent'), ('D', 'Delivered'), ('F', 'Failed')], db_index=True, default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='communication',
            name='subject',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CommunicationTemplate'),
        ),
        migrations.AddField(
            model_name='communicationstatus',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Communication'),
        ),
    ]
