# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 17:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171031_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='recipient_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, db_index=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='communication',
            name='send_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
