# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-29 20:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180122_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='backends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=[], help_text='An array of backends to try use to send. Will try in order until one is successful', null=True, size=None),
        ),
        migrations.AddField(
            model_name='communication',
            name='channel',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='preferred_transport',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('notification', 'Push Notification')], default='email', max_length=10),
        ),
    ]
