# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-03 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180122_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='cancel_signal',
            field=models.BooleanField(default=False),
        ),
    ]
