# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-30 10:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180629_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Communication'),
        ),
        migrations.AddField(
            model_name='communication',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=[], null=True, size=None),
        ),
    ]
