# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-30 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180630_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('Q', 'Queued'), ('S', 'Sent'), ('D', 'Delivered'), ('O', 'Opened'), ('C', 'Clicked'), ('UK', 'Unknown'), ('F', 'Failed')], db_index=True, default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='communicationstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('Q', 'Queued'), ('S', 'Sent'), ('D', 'Delivered'), ('O', 'Opened'), ('C', 'Clicked'), ('UK', 'Unknown'), ('F', 'Failed')], db_index=True, default='N', max_length=255, null=True),
        ),
    ]
