# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-03 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180203_1428'),
        ('api', '0012_communication_cancel_signal'),
    ]

    operations = [
    ]
