# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 09:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20180630_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='A longer description of the purpose of this communication', null=True),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='name',
            field=models.CharField(blank=True, help_text='A friendly name describing what this template is for', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='slug',
            field=models.SlugField(blank=True, help_text='A friendly lookup for this template', null=True),
        ),
        migrations.AlterField(
            model_name='communicationtemplate',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Build schemas at: https://jsonschema.net', null=True),
        ),
        migrations.AlterField(
            model_name='communicationtemplate',
            name='template_base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='communicationtemplate',
            unique_together=set([('owner', 'slug')]),
        ),
    ]
