# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180703_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='short_message',
            field=models.TextField(blank=True, help_text='Used for short messages', null=True),
        ),
        migrations.AlterField(
            model_name='communicationtemplate',
            name='short_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
