# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-05 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180703_0948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communicationtemplate',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='communicationtemplate',
            name='owner',
        ),
    ]
