# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-05 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180705_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationtemplate',
            name='owner',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
