# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_communicationtemplate_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='template_slug',
            field=models.SlugField(blank=True, help_text='A lookup on communicationtemplate', null=True),
        ),
    ]
