# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-09 11:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_communication_template_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='unknown', max_length=12)),
                ('backend', models.CharField(blank=True, max_length=255, null=True)),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
