{% with rabbit_password = 9999999999999999999999 | random | to_uuid %}
---
version: '3'

services:
  {{docker_service}}_worker:
    image: {{docker_org}}/{{docker_image}}:{{docker_version}}
    command: celery -A communications worker -l info
    networks:
      - kong
    deploy:
        replicas: {{docker_replicas}}
        update_config:
          parallelism: 1
          delay: 30s
{% for var in docker_environment %}
      - {{var.key}}={{var.value}}
{% endfor %}
  {{docker_service}}:
    image: {{docker_org}}/{{docker_image}}:{{docker_version}}
    command: sh /code/run.sh
    networks:
      - kong
    deploy:
        replicas: {{docker_replicas}}
        update_config:
          parallelism: 1
          delay: 30s
{% for var in docker_environment %}
      - {{var.key}}={{var.value}}
{% endfor %}
  {{docker_service}}_backup:
    image: appointmentguru/pgbackups
    command: sh /backup.sh
    networks:
      - kong
    deploy:
      restart_policy:
        condition: any
        delay: 12h
    environment:
      - BUCKET_NAME=dbbackups.appointmentguru
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID={{aws_access_key}}
      - AWS_SECRET_ACCESS_KEY={{aws_secret_key}}
      - PGDATABASE={{organization}}_{{service}}
      - PGUSER={{organization}}_{{service}}
      - PGHOST={{postgres_db_host}}
      - PGPASSWORD={{postgres_passwords[service]}}
networks:
  kong:
    external:
      name: infrastructure_internal
{% endwith %}
